[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
authors = ["Carlos Alberto Filho <carlosalberto_filho@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
